### ISSUE TITLE
(v.5.0.3) - RTC Corruptor Launcher issue

### ISSUE THREAD

**Issue by Masternama-8000** [ircluzar/RTCV#1]
I can't install file:

![rtc error downloder](https://user-images.githubusercontent.com/54476488/71312479-74474480-2451-11ea-913d-b566a559f46a.png)

Microsoft. NET. Framework is not supported OS :(

![net error](https://user-images.githubusercontent.com/54476488/71312502-b1abd200-2451-11ea-8b14-9a949e94dcae.png)

![missing rtc](https://user-images.githubusercontent.com/54476488/71312513-c6886580-2451-11ea-9e9e-f73bd1af8e45.png)

**OS:** Windows 7 Basic Home
**Device:** HP Pavilion G4

**Comment by ircluzar** [comment]
Sorry, your operating system is too old.
.Net 4.8 will not run on Windows 7

You need a computer that runs Windows 10.

**Comment by NarryG** [comment]
Install SP1 and it should work.
